### ISSUE TITLE
Trying to execute post-publishment commands fails

### ISSUE THREAD

**Issue by HunteRoi** [Rolanddoda/deploy-react-to-gh-pages#1]
`rm` is not recognized as an internal command so it won't execute. Due to this, the clean part of the workflow is broken on my end.

Any idea why it does not work properly?

```bash
Command failed with ENOENT: rm -r build
spawn rm ENOENT
'rm' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 deploy: `node scripts/gh-pages-deploy.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Rolanddoda** [comment]
Hi @HunteRoi, this repo is an example on how I implemented [this](article). So if you found an issue following the article you should not open an issue here.

From the error I suspect that you don't have Git Bash installed on your machine. I assume you are using windows and the `rm` command should be `del` in order to work. But if you install [Git bash](https://git-scm.com/download/win) everything should work fine.

However, even if you don't have git bash and you follow the article until the end still everything will work since the `gh-pages-deploy` script will run in github actions runner.
